### PR TITLE
Added animation for k-means

### PR DESCRIPTION
**Pull request by andersle**
This PR will add one example that I showed during lecture 5. I only showed the generated figures, and this PR will add the source code to generate the images, as requested after the lecture by a student.

It will also show an animated version.

Binder: https://mybinder.org/v2/gh/andersle/chemometrics/add_extra_example_lecture_005

### CODE REVIEW

**Comment by andersle** [comment]
@sroet: This one is ready for a review.

**Comment by sroet** [comment]
please add the magic `%%capture` to cell 8 (and maybe also cell 7) to not output any of the extra figures?

**Comment by andersle** [comment]
@sroet: Added capture to cell 8 now.

**Comment by sroet** [comment]
LGTM, merging

**Pull request merged**
